services:
  archipelago:
    container_name: archipelago
    build:
      context: ./docker/archipelago
      dockerfile: Dockerfile
    image: archipelago
    volumes:
      - ./players:/Archipelago/Players
      - ./output:/Archipelago/output
    ports:
      - 38281:38281
